name: Build Windows EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4 # Updated to v4
      
      - name: Set up Python
        uses: actions/setup-python@v5 # Updated to v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          pip install flask pyinstaller
          
    - name: Build EXE
            run: |
              pip install flask pyinstaller
              pyinstaller --noconflict --noconsole `
              --add-data "templates;templates" `
              --add-data "static;static" `
              --add-data "db.sqlite;." `
              --hidden-import=database_manager `
              --onefile app.py
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # Fixed the error here
        with:
          name: LibreriaPro-Windows-EXE
          path: dist/app.exe
